/**
 * Provider-free, per-page inspection publication for one current Image2 plan.
 *
 * This module receives only adapter-compiled facts. It does not parse source,
 * resolve presentation, compile provider prose, render headers, or consult a
 * former derived tree. The published tree is therefore an inspection
 * projection, never an input or lifecycle owner.
 */
import { randomBytes } from "node:crypto";
import {
  lstatSync,
  mkdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";

import { canonicalJson, canonicalJsonSha256 } from "../identity/canonical_json.mjs";
import { sha256Bytes } from "../identity/byte_hash.mjs";
import { validateRawWorkPlan } from "./page_image_artifacts.mjs";
import { validateProgressiveRawWorkPlan } from "./page_image_progressive_schema.mjs";
import {
  PAGE_DERIVED_ARTIFACT_FILENAMES,
  pageImageDerivedPagePaths,
  pageImageWorkflowPaths,
} from "../run-bundle/page_image_paths.mjs";

export const PAGE_DERIVED_DATA_ARTIFACT_SCHEMA = "page-image-page-derived-artifact";
export const PAGE_DERIVED_DATA_INDEX_SCHEMA = "page-image-page-derived-index";
export const PAGE_DERIVED_DATA_PRODUCER = "scripts/shared/image2/page_derived_data.mjs";

const WORKFLOWS = new Set(["framed", "pure"]);
const SHA256_RE = /^[0-9a-f]{64}$/;
const SLIDE_ID_RE = /^[A-Za-z][A-Za-z0-9_-]{0,63}$/;
const DEFAULT_FILESYSTEM = Object.freeze({
  lstatSync,
  mkdirSync,
  renameSync,
  rmSync,
  writeFileSync,
});

const STAGE_DETAILS = Object.freeze({
  "page-source-receipt": Object.freeze({
    role: "parsed-source",
    purpose: "Preserve the parser-owned normalized facts for one current page.",
    adjustment_scope: "authored page source and selected visual-language facts",
    downstream_controller: "selected Page Image adapter compilation",
    rebuild_impact: "A source or parser binding change requires the current image2 plan to be rebuilt.",
  }),
  "page-layout": Object.freeze({
    role: "resolved-presentation",
    purpose: "Expose the selected workflow-isolated Page Class projection and its provenance.",
    adjustment_scope: "selected Page Class profile and version presentation defaults",
    downstream_controller: "selected Page Image adapter compilation",
    rebuild_impact: "A selected profile, default, class, or provenance change requires the current image2 plan to be rebuilt.",
  }),
  "page-render-model": Object.freeze({
    role: "reviewable-page",
    purpose: "Describe the complete pre-provider page composition without provider request bytes.",
    adjustment_scope: "parsed content, selected visual treatment, and resolved page layout",
    downstream_controller: "Complete Page Review preparation",
    rebuild_impact: "A receipt, visual selection, layout, or local Framed header change requires the current image2 plan to be rebuilt.",
  }),
  "page-generation-spec": Object.freeze({
    role: "compiled-page-facts",
    purpose: "Preserve the Page Image Core semantics that the selected adapter bound to this page.",
    adjustment_scope: "Core semantic facts, selected style, generation profile, and header policy",
    downstream_controller: "selected adapter provider-input compilation",
    rebuild_impact: "Any Core semantic or selected configuration binding change requires the current image2 plan to be rebuilt.",
  }),
  "image2-request": Object.freeze({
    role: "provider-input",
    purpose: "Expose the exact selected-adapter canonical UTF-8 request bytes before authorization.",
    adjustment_scope: "selected adapter compilation and its bound Core generation facts",
    downstream_controller: "existing progressive raw-plan owner",
    rebuild_impact: "A request byte, raw-contract, or Core binding change requires the current image2 plan to be rebuilt before authorization.",
  }),
  "framed-header-html": Object.freeze({
    role: "local-header-overlay",
    purpose: "Expose the exact deterministic Framed local header renderer output.",
    adjustment_scope: "Framed local header policy and selected Page Class profile",
    downstream_controller: "Framed local composition",
    rebuild_impact: "A Framed header policy or selected profile change requires the current image2 plan to be rebuilt.",
  }),
  "page-artifact-index": Object.freeze({
    role: "page-derived-index",
    purpose: "Locate one page's independently published pre-provider artifacts without becoming lifecycle state.",
    adjustment_scope: "all page-local C5 planning artifacts",
    downstream_controller: "Agent inspection only",
    rebuild_impact: "Replacing any referenced page artifact requires the page index to be regenerated by image2 plan.",
  }),
  "deck-derived-index": Object.freeze({
    role: "deck-derived-index",
    purpose: "Locate current page artifact indexes by stable identity and current position.",
    adjustment_scope: "the complete ordered C5 plan publication",
    downstream_controller: "Agent inspection only",
    rebuild_impact: "Any page-set, ordering, source, workflow, or plan-lineage change requires the deck index to be regenerated by image2 plan.",
  }),
});

export class PageDerivedDataError extends Error {
  constructor(code, message) {
    super(message);
    this.name = "PageDerivedDataError";
    this.code = code;
  }
}

function fail(code, message) {
  throw new PageDerivedDataError(code, message);
}

function isPlainObject(value) {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function same(left, right) {
  return canonicalJson(left) === canonicalJson(right);
}

function digest(value, label) {
  if (typeof value !== "string" || !SHA256_RE.test(value)) fail("page_derived_data_invalid", `${label} must be a lowercase SHA-256`);
  return value;
}

function slideId(value, label = "slide_id") {
  if (typeof value !== "string" || !SLIDE_ID_RE.test(value)) fail("page_derived_data_invalid", `${label} must be one safe stable slide ID`);
  return value;
}

function workflow(value) {
  if (!WORKFLOWS.has(value)) fail("page_derived_data_invalid", "workflow must be framed or pure");
  return value;
}

function sourceReceipt(value, expectedWorkflow) {
  if (!isPlainObject(value) || value.schema !== "page-image-workflow-source" || value.pipeline !== "page-image-workflow" ||
    value.workflow !== expectedWorkflow || !Array.isArray(value.slides) || value.slides.length === 0) {
    fail("page_derived_data_source_invalid", "page-derived publication requires one selected parser-owned source receipt");
  }
  digest(value.source_sha256, "source_sha256");
  const ids = new Set();
  value.slides.forEach((page, index) => {
    if (!isPlainObject(page) || slideId(page.slide_id) !== page.slide_id || page.position !== index + 1 || ids.has(page.slide_id) ||
      Object.hasOwn(page, "workflow") || Object.hasOwn(page, "authority")) {
      fail("page_derived_data_source_invalid", "source receipt pages must retain unique ordered stable IDs without page workflow authority");
    }
    ids.add(page.slide_id);
  });
  return value;
}

function rawPlan(value, receipt, expectedWorkflow) {
  const checked = validateRawWorkPlan(value);
  if (!checked.ok || value.workflow !== expectedWorkflow || value.source_receipt_sha256 !== receipt.source_sha256 ||
    !same(value.ordered_slide_ids, receipt.slides.map((page) => page.slide_id))) {
    fail("page_derived_data_raw_plan_invalid", "page-derived publication requires the exact selected raw work plan");
  }
  return Object.freeze({ plan: value, sha256: checked.sha256 });
}

function progressivePlan(value, receipt, raw, expectedWorkflow) {
  const checked = validateProgressiveRawWorkPlan(value);
  if (!checked.ok || value.workflow !== expectedWorkflow || value.source_receipt_sha256 !== receipt.source_sha256 ||
    !same(value.ordered_slide_ids, raw.plan.ordered_slide_ids) || !same(value.items, raw.plan.items) ||
    value.provider_profile_sha256 !== raw.plan.provider_profile_sha256) {
    fail("page_derived_data_progressive_plan_invalid", "page-derived publication requires the exact current progressive raw-plan candidate");
  }
  return Object.freeze({ plan: value, sha256: checked.sha256 });
}

function coreFacts(value, receipt, expectedWorkflow) {
  if (!isPlainObject(value) || value.schema !== "page-image-core-facts" || value.workflow !== expectedWorkflow ||
    value.source_receipt_sha256 !== receipt.source_sha256 || !Array.isArray(value.slides) || value.slides.length !== receipt.slides.length) {
    fail("page_derived_data_core_invalid", "page-derived publication requires current Page Image Core facts for every receipt page");
  }
  const slides = new Map();
  for (const [index, page] of value.slides.entries()) {
    const receiptPage = receipt.slides[index];
    if (!isPlainObject(page) || page.schema !== "page-image-core-slide-facts" || page.workflow !== expectedWorkflow ||
      page.slide_id !== receiptPage.slide_id || page.position !== receiptPage.position ||
      page.source_receipt_sha256 !== receipt.source_sha256 || !digest(page.canonical_semantic_sha256, "core canonical_semantic_sha256")) {
      fail("page_derived_data_core_invalid", "Page Image Core facts must retain one exact receipt page identity and semantic digest");
    }
    slides.set(page.slide_id, page);
  }
  return Object.freeze({ facts: value, slides });
}

function requestForPage(value, page, rawItem, corePage, expectedWorkflow) {
  if (!isPlainObject(value) || value.slide_id !== page.slide_id || typeof value.schema !== "string" ||
    value.raw_contract_sha256 !== rawItem.raw_contract_sha256 || !isPlainObject(value.compiled_provider_input) ||
    typeof value.compiled_provider_input.utf8 !== "string" || value.compiled_provider_input.utf8.length === 0) {
    fail("page_derived_data_request_invalid", `selected adapter request is invalid for ${page.slide_id}`);
  }
  const compiled = value.compiled_provider_input;
  digest(compiled.sha256, "compiled_provider_input.sha256");
  if (sha256Bytes(Buffer.from(compiled.utf8, "utf8")) !== compiled.sha256 ||
    compiled.sha256 !== rawItem.provider_input_binding.compiled_provider_input_sha256 ||
    canonicalJsonSha256(value.generation_profile) !== rawItem.provider_input_binding.generation_profile_sha256 ||
    rawItem.provider_input_binding.provider_content_sha256 !== corePage.provider_content_sha256 ||
    rawItem.provider_input_binding.visual_selection_sha256 !== corePage.visual_selection_sha256 ||
    rawItem.provider_input_binding.page_presentation_sha256 !== corePage.page_presentation_sha256) {
    fail("page_derived_data_request_invalid", `selected adapter request bindings do not match ${page.slide_id}`);
  }
  return value;
}

function headerHtmlBySlide(value, orderedIds, expectedWorkflow) {
  if (expectedWorkflow === "pure") {
    if (value !== null && value !== undefined) fail("page_derived_data_header_invalid", "Pure publication must not supply Framed header HTML");
    return new Map();
  }
  if (!isPlainObject(value) || !same(Object.keys(value).sort(), [...orderedIds].sort())) {
    fail("page_derived_data_header_invalid", "Framed publication requires one renderer-produced HTML document for every current page");
  }
  const output = new Map();
  for (const id of orderedIds) {
    const html = value[id];
    if (typeof html !== "string" || !html.startsWith("<!doctype html>")) {
      fail("page_derived_data_header_invalid", `Framed header HTML is invalid for ${id}`);
    }
    output.set(id, html);
  }
  return output;
}

function publicationInput(input) {
  if (!isPlainObject(input)) fail("page_derived_data_invalid", "page-derived publication input must be an object");
  const expectedWorkflow = workflow(input.workflow);
  const receipt = sourceReceipt(input.receipt, expectedWorkflow);
  const raw = rawPlan(input.raw_work_plan, receipt, expectedWorkflow);
  const progressive = progressivePlan(input.progressive_raw_work_plan, receipt, raw, expectedWorkflow);
  const core = coreFacts(input.page_image_core, receipt, expectedWorkflow);
  if (!isPlainObject(input.provider_requests_by_slide) || !same(Object.keys(input.provider_requests_by_slide).sort(), [...raw.plan.ordered_slide_ids].sort())) {
    fail("page_derived_data_request_invalid", "selected adapter requests must cover the exact current plan pages");
  }
  const requests = new Map();
  const items = new Map(raw.plan.items.map((item) => [item.slide_id, item]));
  for (const page of receipt.slides) {
    requests.set(page.slide_id, requestForPage(input.provider_requests_by_slide[page.slide_id], page, items.get(page.slide_id), core.slides.get(page.slide_id), expectedWorkflow));
  }
  const headers = headerHtmlBySlide(input.framed_header_html_by_slide, raw.plan.ordered_slide_ids, expectedWorkflow);
  return Object.freeze({
    run_dir: resolve(String(input.run_dir || "")),
    workflow: expectedWorkflow,
    receipt,
    raw,
    progressive,
    core,
    requests,
    headers,
  });
}

function artifactEnvelope({ stage, page, publication, payload, upstream_bindings, invalidated_by }) {
  const details = STAGE_DETAILS[stage];
  if (!details) fail("page_derived_data_invalid", `unknown C5 stage ${stage}`);
  return {
    schema: PAGE_DERIVED_DATA_ARTIFACT_SCHEMA,
    stage,
    role: details.role,
    producer: PAGE_DERIVED_DATA_PRODUCER,
    purpose: details.purpose,
    adjustment_scope: details.adjustment_scope,
    downstream_controller: details.downstream_controller,
    rebuild_impact: details.rebuild_impact,
    page: { slide_id: page.slide_id, position: page.position },
    publication,
    upstream_bindings,
    digest: { algorithm: "sha256", payload_sha256: canonicalJsonSha256(payload) },
    invalidated_by,
    payload,
  };
}

function relativeArtifactPath(pageId, filename) {
  slideId(pageId);
  return `pages/${pageId}/${filename}`;
}

function pagePublication(page, input) {
  const core = input.core.slides.get(page.slide_id);
  const item = input.raw.plan.items[page.position - 1];
  const request = input.requests.get(page.slide_id);
  const layout = page.visual_language?.presentation;
  if (!isPlainObject(layout) || layout.workflow !== input.workflow || layout.page_class !== page.page_class ||
    !digest(layout.binding_sha256, "page presentation binding_sha256")) {
    fail("page_derived_data_layout_invalid", `resolved Page Class presentation is invalid for ${page.slide_id}`);
  }
  const publication = {
    workflow: input.workflow,
    source_receipt_sha256: input.receipt.source_sha256,
    raw_work_plan_sha256: input.raw.sha256,
    progressive_raw_work_plan_sha256: input.progressive.sha256,
    source_epoch: input.progressive.plan.source_epoch,
  };
  const sharedInvalidation = {
    source_sha256: input.receipt.source_sha256,
    workflow: input.workflow,
    page_presentation_binding_sha256: layout.binding_sha256,
    core_semantic_sha256: core.canonical_semantic_sha256,
    raw_contract_sha256: item.raw_contract_sha256,
    progressive_raw_work_plan_sha256: input.progressive.sha256,
  };
  const source = artifactEnvelope({
    stage: "page-source-receipt",
    page,
    publication,
    upstream_bindings: {
      source_sha256: input.receipt.source_sha256,
      visual_selection_sha256: core.visual_selection_sha256,
    },
    invalidated_by: { source_sha256: input.receipt.source_sha256, workflow: input.workflow },
    payload: { parsed_page: page },
  });
  const pageLayout = artifactEnvelope({
    stage: "page-layout",
    page,
    publication,
    upstream_bindings: {
      source_receipt_sha256: input.receipt.source_sha256,
      page_presentation_binding_sha256: layout.binding_sha256,
      visual_selection_sha256: core.visual_selection_sha256,
    },
    invalidated_by: sharedInvalidation,
    payload: {
      page_class: page.page_class,
      selected_presentation: layout,
    },
  });
  const header = input.headers.get(page.slide_id) || null;
  const renderModel = artifactEnvelope({
    stage: "page-render-model",
    page,
    publication,
    upstream_bindings: {
      source_receipt_sha256: input.receipt.source_sha256,
      page_presentation_binding_sha256: layout.binding_sha256,
      visual_selection_sha256: core.visual_selection_sha256,
      ...(header ? { framed_header_html_sha256: sha256Bytes(Buffer.from(header, "utf8")) } : {}),
    },
    invalidated_by: sharedInvalidation,
    payload: {
      page_class: page.page_class,
      parsed_content: {
        header_policy: page.header_policy,
        provider_content: page.provider_content,
      },
      visual_selection: page.visual_language,
      resolved_layout: {
        page_class: page.page_class,
        profile_id: layout.profile_id,
        binding_sha256: layout.binding_sha256,
        provenance: layout.provenance,
      },
      ...(header ? { local_header_representation: { format: "html", path: relativeArtifactPath(page.slide_id, PAGE_DERIVED_ARTIFACT_FILENAMES.framed_header_html) } } : {}),
    },
  });
  const generation = artifactEnvelope({
    stage: "page-generation-spec",
    page,
    publication,
    upstream_bindings: {
      source_receipt_sha256: input.receipt.source_sha256,
      canonical_semantic_sha256: core.canonical_semantic_sha256,
      provider_content_sha256: core.provider_content_sha256,
      visual_selection_sha256: core.visual_selection_sha256,
      style_master_selection_sha256: core.style_master_selection_sha256,
      generation_profile_sha256: core.generation_profile_sha256,
      header_policy_sha256: core.header_policy_sha256,
      page_presentation_sha256: core.page_presentation_sha256,
    },
    invalidated_by: sharedInvalidation,
    payload: { core_facts: core },
  });
  const imageRequest = artifactEnvelope({
    stage: "image2-request",
    page,
    publication,
    upstream_bindings: {
      raw_contract_sha256: item.raw_contract_sha256,
      compiled_provider_input_sha256: item.provider_input_binding.compiled_provider_input_sha256,
      canonical_semantic_sha256: core.canonical_semantic_sha256,
      generation_profile_sha256: item.provider_input_binding.generation_profile_sha256,
    },
    invalidated_by: sharedInvalidation,
    payload: {
      request_schema: request.schema,
      canonical_utf8: request.compiled_provider_input.utf8,
      request_digest: request.compiled_provider_input.sha256,
      adapter_binding: item.provider_input_binding,
      raw_contract_sha256: item.raw_contract_sha256,
    },
  });
  return Object.freeze({ page, publication, source, layout: pageLayout, render_model: renderModel, generation_spec: generation, image2_request: imageRequest, header_html: header });
}

function fileBytes(value) {
  return Buffer.from(`${canonicalJson(value)}\n`, "utf8");
}

function safeRelative(root, pathname) {
  const result = relative(root, pathname).replaceAll("\\", "/");
  if (!result || result === ".." || result.startsWith("../") || isAbsolute(result)) {
    fail("page_derived_data_path_invalid", "published page-derived path must remain inside its derived root");
  }
  return result;
}

function isChild(root, target) {
  const relation = relative(root, target);
  return Boolean(relation && relation !== ".." && !relation.startsWith(`..${sep}`) && !isAbsolute(relation));
}

function filesystemFrom(options) {
  if (options === undefined) return DEFAULT_FILESYSTEM;
  if (!isPlainObject(options) || !isPlainObject(options.filesystem)) fail("page_derived_data_invalid", "publication options must supply a filesystem object");
  const filesystem = { ...DEFAULT_FILESYSTEM, ...options.filesystem };
  for (const key of Object.keys(DEFAULT_FILESYSTEM)) if (typeof filesystem[key] !== "function") fail("page_derived_data_invalid", "publication filesystem is invalid");
  return filesystem;
}

function optionalLstat(filesystem, pathname) {
  try {
    return filesystem.lstatSync(pathname);
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
}

function requireDirectory(filesystem, pathname, label) {
  const stats = optionalLstat(filesystem, pathname);
  if (!stats || !stats.isDirectory() || stats.isSymbolicLink()) fail("page_derived_data_path_invalid", `${label} must be a non-symbolic-link directory`);
  return pathname;
}

function ensureDirectory(filesystem, root, target, label) {
  if (!isChild(root, target) && resolve(root) !== resolve(target)) fail("page_derived_data_path_invalid", `${label} escapes the current run`);
  const parts = relative(root, target).split(sep).filter(Boolean);
  let current = root;
  requireDirectory(filesystem, current, "current run directory");
  for (const part of parts) {
    if (!/^[A-Za-z0-9._-]+$/.test(part)) fail("page_derived_data_path_invalid", `${label} has an unsafe path component`);
    current = join(current, part);
    const stats = optionalLstat(filesystem, current);
    if (!stats) {
      filesystem.mkdirSync(current);
    } else if (!stats.isDirectory() || stats.isSymbolicLink()) {
      fail("page_derived_data_path_invalid", `${label} must not traverse a symbolic link or regular file`);
    }
  }
  return requireDirectory(filesystem, target, label);
}

function randomSibling(parent, label) {
  return join(parent, `.${label}-${randomBytes(8).toString("hex")}`);
}

function createStageRoot(filesystem, paths, runDir) {
  const parent = ensureDirectory(filesystem, runDir, dirname(paths.derived_root), "Page Image generated root");
  for (let attempt = 0; attempt < 16; attempt += 1) {
    const stage = randomSibling(parent, "derived-stage");
    try {
      filesystem.mkdirSync(stage);
      return requireDirectory(filesystem, stage, "page-derived staging root");
    } catch (error) {
      if (error?.code !== "EEXIST") throw error;
    }
  }
  fail("page_derived_data_publish_failed", "could not allocate a private page-derived staging root");
}

function stageWrite(filesystem, root, relativePath, bytes) {
  const pathname = join(root, ...relativePath.split("/"));
  const parent = dirname(pathname);
  ensureDirectory(filesystem, root, parent, "page-derived staging directory");
  if (!isChild(root, pathname)) fail("page_derived_data_path_invalid", "page-derived file escapes its staging root");
  filesystem.writeFileSync(pathname, bytes, { mode: 0o644, flag: "wx" });
  const stats = optionalLstat(filesystem, pathname);
  if (!stats || !stats.isFile() || stats.isSymbolicLink()) fail("page_derived_data_publish_failed", "page-derived staged file is unavailable");
  return Object.freeze({ path: pathname, sha256: sha256Bytes(bytes), bytes });
}

function pageIndex(pageArtifacts, stagedFiles) {
  const { page, publication } = pageArtifacts;
  const references = {};
  for (const key of ["source_receipt", "layout", "render_model", "generation_spec", "image2_request"]) {
    const filename = PAGE_DERIVED_ARTIFACT_FILENAMES[key];
    const reference = stagedFiles.get(relativeArtifactPath(page.slide_id, filename));
    references[key] = { path: relativeArtifactPath(page.slide_id, filename), sha256: reference.sha256 };
  }
  if (pageArtifacts.header_html !== null) {
    const filename = PAGE_DERIVED_ARTIFACT_FILENAMES.framed_header_html;
    const reference = stagedFiles.get(relativeArtifactPath(page.slide_id, filename));
    references.framed_header_html = {
      path: relativeArtifactPath(page.slide_id, filename),
      sha256: reference.sha256,
      format: "html",
      producer: PAGE_DERIVED_DATA_PRODUCER,
      purpose: STAGE_DETAILS["framed-header-html"].purpose,
      adjustment_scope: STAGE_DETAILS["framed-header-html"].adjustment_scope,
      downstream_controller: STAGE_DETAILS["framed-header-html"].downstream_controller,
      rebuild_impact: STAGE_DETAILS["framed-header-html"].rebuild_impact,
      invalidated_by: pageArtifacts.render_model.invalidated_by,
    };
  }
  return artifactEnvelope({
    stage: "page-artifact-index",
    page,
    publication,
    upstream_bindings: {
      source_receipt_sha256: publication.source_receipt_sha256,
      raw_work_plan_sha256: publication.raw_work_plan_sha256,
      progressive_raw_work_plan_sha256: publication.progressive_raw_work_plan_sha256,
    },
    invalidated_by: pageArtifacts.render_model.invalidated_by,
    payload: {
      artifact_references: references,
      lifecycle_observation: "available-for-agent-inspection-at-image2-plan-only",
    },
  });
}

function deckIndex(input, pageIndexes) {
  const details = STAGE_DETAILS["deck-derived-index"];
  const payload = {
    pages: pageIndexes.map(({ page, reference }) => ({
      slide_id: page.slide_id,
      position: page.position,
      page_artifact_index: { path: reference.path, sha256: reference.sha256 },
    })),
    lifecycle_observation: "available-for-agent-inspection-at-image2-plan-only",
  };
  return {
    schema: PAGE_DERIVED_DATA_INDEX_SCHEMA,
    stage: "deck-derived-index",
    role: details.role,
    producer: PAGE_DERIVED_DATA_PRODUCER,
    purpose: details.purpose,
    adjustment_scope: details.adjustment_scope,
    downstream_controller: details.downstream_controller,
    rebuild_impact: details.rebuild_impact,
    publication: {
      workflow: input.workflow,
      source_receipt_sha256: input.receipt.source_sha256,
      raw_work_plan_sha256: input.raw.sha256,
      progressive_raw_work_plan_sha256: input.progressive.sha256,
      source_epoch: input.progressive.plan.source_epoch,
    },
    upstream_bindings: {
      source_receipt_sha256: input.receipt.source_sha256,
      raw_work_plan_sha256: input.raw.sha256,
      progressive_raw_work_plan_sha256: input.progressive.sha256,
    },
    digest: { algorithm: "sha256", payload_sha256: canonicalJsonSha256(payload) },
    invalidated_by: {
      source_sha256: input.receipt.source_sha256,
      workflow: input.workflow,
      progressive_raw_work_plan_sha256: input.progressive.sha256,
    },
    payload,
  };
}

function assertStagedTree(filesystem, stageRoot, expected) {
  requireDirectory(filesystem, stageRoot, "page-derived staging root");
  for (const record of expected.values()) {
    const stats = optionalLstat(filesystem, record.path);
    if (!stats || !stats.isFile() || stats.isSymbolicLink() || sha256Bytes(record.bytes) !== record.sha256) {
      fail("page_derived_data_publish_failed", "page-derived staging tree is incomplete or invalid");
    }
  }
}

function restorePrevious(filesystem, previous, canonical) {
  if (!previous || optionalLstat(filesystem, canonical)) return false;
  try {
    filesystem.renameSync(previous, canonical);
    return true;
  } catch {
    return false;
  }
}

function replaceTree(filesystem, paths, stageRoot) {
  const parent = dirname(paths.derived_root);
  const canonical = paths.derived_root;
  const existing = optionalLstat(filesystem, canonical);
  if (existing && (!existing.isDirectory() || existing.isSymbolicLink())) {
    fail("page_derived_data_path_invalid", "existing page-derived root must be a non-symbolic-link directory");
  }
  let previous = null;
  try {
    if (existing) {
      previous = randomSibling(parent, "derived-previous");
      filesystem.renameSync(canonical, previous);
    }
    filesystem.renameSync(stageRoot, canonical);
  } catch (error) {
    if (!restorePrevious(filesystem, previous, canonical)) {
      fail("page_derived_data_publish_failed", "page-derived replacement failed before the previous tree could be restored");
    }
    fail("page_derived_data_publish_failed", "page-derived replacement failed and the previous tree was preserved");
  }
  requireDirectory(filesystem, canonical, "published page-derived root");
  if (previous) {
    try {
      filesystem.rmSync(previous, { recursive: true, force: true });
    } catch {
      // A stale private sibling is not current publication input or authority.
    }
  }
}

/**
 * Publish one complete provider-free C5 inspection tree for a selected adapter
 * candidate. This synchronous writer does not initialize provider transport or
 * alter lifecycle state; callers invoke it before progressive-plan publication.
 */
export function publishPageDerivedData(input, options = undefined) {
  const checked = publicationInput(input);
  const filesystem = filesystemFrom(options);
  const paths = pageImageWorkflowPaths(checked.run_dir);
  const stageRoot = createStageRoot(filesystem, paths, checked.run_dir);
  const staged = new Map();
  try {
    const pages = checked.receipt.slides.map((page) => pagePublication(page, checked));
    for (const artifacts of pages) {
      const artifactsByFilename = [
        [PAGE_DERIVED_ARTIFACT_FILENAMES.source_receipt, artifacts.source],
        [PAGE_DERIVED_ARTIFACT_FILENAMES.layout, artifacts.layout],
        [PAGE_DERIVED_ARTIFACT_FILENAMES.render_model, artifacts.render_model],
        [PAGE_DERIVED_ARTIFACT_FILENAMES.generation_spec, artifacts.generation_spec],
        [PAGE_DERIVED_ARTIFACT_FILENAMES.image2_request, artifacts.image2_request],
      ];
      if (artifacts.header_html !== null) artifactsByFilename.push([PAGE_DERIVED_ARTIFACT_FILENAMES.framed_header_html, artifacts.header_html]);
      for (const [filename, artifact] of artifactsByFilename) {
        const artifactPath = relativeArtifactPath(artifacts.page.slide_id, filename);
        const bytes = typeof artifact === "string" ? Buffer.from(artifact, "utf8") : fileBytes(artifact);
        staged.set(artifactPath, stageWrite(filesystem, stageRoot, artifactPath, bytes));
      }
    }
    const pageIndexes = pages.map((artifacts) => {
      const index = pageIndex(artifacts, staged);
      const path = relativeArtifactPath(artifacts.page.slide_id, PAGE_DERIVED_ARTIFACT_FILENAMES.artifact_index);
      const reference = stageWrite(filesystem, stageRoot, path, fileBytes(index));
      staged.set(path, reference);
      return Object.freeze({ page: artifacts.page, reference, index });
    });
    const index = deckIndex(checked, pageIndexes.map(({ page, reference }) => ({
      page,
      reference: { path: safeRelative(stageRoot, reference.path), sha256: reference.sha256 },
    })));
    const indexRecord = stageWrite(filesystem, stageRoot, "index.json", fileBytes(index));
    staged.set("index.json", indexRecord);
    assertStagedTree(filesystem, stageRoot, staged);
    replaceTree(filesystem, paths, stageRoot);
    return Object.freeze({
      root: paths.derived_root,
      index: paths.derived_index,
      workflow: checked.workflow,
      source_receipt_sha256: checked.receipt.source_sha256,
      raw_work_plan_sha256: checked.raw.sha256,
      progressive_raw_work_plan_sha256: checked.progressive.sha256,
      pages: Object.freeze(pageIndexes.map(({ page, reference }) => Object.freeze({
        slide_id: page.slide_id,
        position: page.position,
        index: pageImageDerivedPagePaths(checked.run_dir, page.slide_id).artifact_index,
        index_sha256: reference.sha256,
      }))),
    });
  } catch (error) {
    try {
      filesystem.rmSync(stageRoot, { recursive: true, force: true });
    } catch {
      // Failed staging must not be promoted or treated as a previous publication.
    }
    if (error instanceof PageDerivedDataError) throw error;
    throw new PageDerivedDataError("page_derived_data_publish_failed", error?.message || "page-derived publication failed before replacement");
  }
}
